import os
import base64
import logging
from typing import Dict, Any, Optional
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from io import BytesIO

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)


def _decode_base64_image(base64_str: str) -> BytesIO:
    img_data = base64.b64decode(base64_str)
    img_io = BytesIO(img_data)
    return img_io


def report_generator_agent(
    summary_data: Dict[str, Any],
    insights_data: Dict[str, Any],
    viz_data: Dict[str, Any],
    output_path: str = "output/data_analysis_report.pdf",
    report_title: str = "Automated Data Analysis Report",
) -> str:
    """
    Generate a professional PDF report using data, insights, and visuals.
    """
    logger.info("Starting report generation...")

    # Create folder if not exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Setup document
    doc = SimpleDocTemplate(output_path, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Custom title style
    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=20,
        leading=24,
        alignment=1,  # Center
        spaceAfter=20,
    )

    # Section header style
    header_style = ParagraphStyle(
        "HeaderStyle",
        parent=styles["Heading2"],
        fontSize=14,
        leading=18,
        spaceAfter=12,
        textColor="#1a237e",
    )

    # Normal paragraph style
    normal_style = ParagraphStyle(
        "NormalStyle",
        parent=styles["Normal"],
        fontSize=11,
        leading=16,
    )

   
    story.append(Paragraph(report_title, title_style))
    story.append(Spacer(1, 12))
    story.append(Paragraph("<b>Generated by:</b> LangGraph Multi-Agent System", normal_style))
    story.append(Paragraph("<b>Modules:</b> Data Parser, Insight Generator, Visualization Agent", normal_style))
    story.append(Spacer(1, 24))

    
    story.append(Paragraph("📊 Dataset Summary", header_style))

    num_rows = summary_data.get("num_rows", "N/A")
    num_cols = summary_data.get("num_columns", "N/A")
    story.append(Paragraph(f"<b>Total Rows:</b> {num_rows}<br/><b>Total Columns:</b> {num_cols}", normal_style))

    story.append(Spacer(1, 12))
    story.append(Paragraph("<b>Columns:</b> " + ", ".join(summary_data.get("columns", [])), normal_style))
    story.append(Spacer(1, 12))

    
    story.append(PageBreak())
    story.append(Paragraph("🧠 Insights & Analysis", header_style))
    text_insights = insights_data.get("text_insights", "No insights available.")
    story.append(Paragraph(text_insights.replace("\n", "<br/>"), normal_style))

    
    story.append(PageBreak())
    story.append(Paragraph("📈 Visualizations", header_style))

    for viz_title, viz_b64 in viz_data.get("visualizations", {}).items():
        story.append(Paragraph(f"<b>{viz_title.replace('_', ' ').title()}</b>", normal_style))
        img_io = _decode_base64_image(viz_b64)
        story.append(Image(img_io, width=5.5 * inch, height=3.5 * inch))
        story.append(Spacer(1, 16))

    
    story.append(PageBreak())
    story.append(Paragraph("✅ Report Summary", header_style))
    story.append(
        Paragraph(
            "This report was automatically generated by a LangGraph-powered multi-agent pipeline. "
            "It includes insights derived from data parsing, LLM reasoning, and statistical visualization.",
            normal_style,
        )
    )

    
    doc.build(story)
    logger.info(f"Report generated successfully: {output_path}")
    return output_path



